Eloenay_Tcc/Eloenay_Tcc/Models/Parcela.cs
using Eloenay_Tcc.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Script.Serialization;

namespace Eloenay_Tcc.Models
{
    public class Parcela
    {
        #region Atributos
        public Guid ParcelaId { get; set; }
        public int IdentificacaoParcela { get; set; }
        public decimal ValorDaParcela { get; set; }
        public decimal ValorPagoDaParcela { get; set; }
        public bool StatusDaParcela { get; set; }
        public DateTime DataDaParcela { get; set; }
        #endregion

        #region Relacionamentos
        public Guid VendaId { get; set; }
        [ScriptIgnore]
        public Venda Venda { get; set; }
        #endregion

        #region Crud
        ParcelaRepository _parcelaRepository = new ParcelaRepository();
        public void Adicionar(Parcela parcelas) => _parcelaRepository.Adicionar(parcelas);
        public void Atualizar(Parcela parcelas) => _parcelaRepository.Atualizar(parcelas);
        public Parcela BuscarPorId(Guid parcelas) => _parcelaRepository.BuscarPorId(parcelas);
        public IEnumerable<Parcela> BuscarPorNome(string nome) => _parcelaRepository.BuscarPorNome(nome);
        public IEnumerable<Parcela> BuscarTodosPorVenda(Guid id) => _parcelaRepository.BuscarTodosPorVenda(id);
        public IEnumerable<Parcela> BuscarTodosPorLoteamento(Guid id) => _parcelaRepository.BuscarTodosPorLoteamento(id);
        public IEnumerable<Parcela> BuscarTodosPorLoteamentoPeriodo(Guid id, int ano, int mes) => _parcelaRepository.BuscarTodosPorLoteamentoPeriodo(id, ano, mes);

        #endregion

        #region Não Mapeados
        public string DataParcelaFormt => DataDaParcela.ToShortDateString();
        public string ValorParcelaFormt => string.Format("{0:#,0.00}", ValorDaParcela);
        public string ValorPagoParcelaFormt => string.Format("{0:#,0.00}", ValorPagoDaParcela);
        #endregion

        #region Métodos
        public decimal ValorDasParcelas(decimal valorLote, decimal valorEntrada, int quantParcelas, double juros)
        {
            decimal jurosConvert = (decimal)juros / 100;
            decimal calculoValorJurosPorMes;
            decimal calculoFinalValorLoteEntradaJuros;
            decimal total;

            if (juros == 0)
            {
                calculoValorJurosPorMes = valorLote + jurosConvert;
            }
            else
            {
                calculoValorJurosPorMes = (valorLote * jurosConvert) + valorLote;
            }
            calculoFinalValorLoteEntradaJuros = calculoValorJurosPorMes - valorEntrada;
            total = calculoFinalValorLoteEntradaJuros / quantParcelas;
            return total;
        }

        public void CriarParcelas(Guid vendaId, DateTime primeiraParcela, int quantParcelas, decimal valorParcelas)
        {
            var dataFim = primeiraParcela;
            var dataInicio = dataFim;
            for (int i = 0; i < quantParcelas; i++)
            {
                var parcelas = new Parcela
                {
                    ParcelaId = Guid.NewGuid(),
                    ValorDaParcela = valorParcelas,
                    IdentificacaoParcela = i + 1,
                    StatusDaParcela = false,
                    DataDaParcela = dataFim.AddMonths(i),
                    VendaId = vendaId
                };
                dataInicio = dataFim;
                Adicionar(parcelas);
            }
        }

        public void AtualizarStatus(bool statusParcela)
        {
            StatusDaParcela = !statusParcela;
        }

        public Parcela ObterValorParcela(Guid id) => _parcelaRepository.ObterValorParcela(id);

        public decimal ObterValorTotalDeParcelas(IEnumerable<Parcela> parcela) => parcela.Where(x => x.Venda.StatusDaVenda == true).Sum(x => x.ValorDaParcela);
        public int ContagemDeTodasAsParcelas(IEnumerable<Parcela> parcela) => parcela.Count(x => x.Venda.StatusDaVenda == true);
        public int ContagemDeParcelasPagas(IEnumerable<Parcela> parcela) => parcela.Count(x => x.Venda.StatusDaVenda == true && x.StatusDaParcela == true);
        public int ContagemDeParcelasPendentes(IEnumerable<Parcela> parcela) => parcela.Count(x => x.Venda.StatusDaVenda == true && x.StatusDaParcela == false && x.DataDaParcela >= DateTime.Now);
        public int ContagemDeParcelasAtrasadas(IEnumerable<Parcela> parcela) => parcela.Count(x => x.Venda.StatusDaVenda == true && x.StatusDaParcela == false && x.DataDaParcela < DateTime.Now);
        public decimal ObterValorDasParcelasPagas(IEnumerable<Parcela> parcela) => parcela.Where(x => x.Venda.StatusDaVenda == true).Sum(x => x.ValorPagoDaParcela);
        public decimal ObterValorDasParcelasPendentes(IEnumerable<Parcela> parcela) => parcela.Where(x => x.Venda.StatusDaVenda == true && x.StatusDaParcela == false && x.DataDaParcela >= DateTime.Now).Sum(x => x.ValorDaParcela);
        public decimal ObterValorDasParcelasAtrasadas(IEnumerable<Parcela> parcela) => parcela.Where(x => x.Venda.StatusDaVenda == true && x.StatusDaParcela == false && x.DataDaParcela < DateTime.Now).Sum(x => x.ValorDaParcela);
        public decimal ObterValorTotalDeParcelasEmVendasCanceladas(IEnumerable<Parcela> parcela) => parcela.Where(x => x.Venda.StatusDaVenda == false).Sum(x => x.ValorDaParcela);
        public int ContagemDeTodasAsParcelasEmVendasCanceladas(IEnumerable<Parcela> parcela) => parcela.Count(x => x.Venda.StatusDaVenda == false);
        public int ContagemDeParcelasPagasEmVendasCanceladas(IEnumerable<Parcela> parcela) => parcela.Count(x => x.Venda.StatusDaVenda == false && x.StatusDaParcela == true);
        public decimal ObterValorDasParcelasPagasEmVendasCanceladas(IEnumerable<Parcela> parcela) => parcela.Where(x => x.Venda.StatusDaVenda == false).Sum(x => x.ValorPagoDaParcela);
        public decimal TotalDeValorRestituido(IEnumerable<Parcela> parcelas)
        {
            var valorParcelas = ObterValorDasParcelasPagasEmVendasCanceladas(parcelas);
            var resultado = (valorParcelas * 70) / 100;
            return resultado;
        }
        #endregion
    }
}

Eloenay_Tcc/Eloenay_Tcc/Controllers/ParcelaController.cs
using Eloenay_Tcc.Models;
using System;
using System.Linq;
using System.Web.Mvc;

namespace Eloenay_Tcc.Controllers
{
    [Authorize]
    public class ParcelaController : Controller
    {
        readonly Parcela _parcelas;
        readonly Venda _venda;

        public ParcelaController(Parcela parcelas, Venda venda)
        {
            _parcelas = parcelas;
            _venda = venda;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Atualizar(Parcela parcelas)
        {
            if (!ModelState.IsValid) return View();
            var parcela = _parcelas.BuscarPorId(parcelas.ParcelaId);
            parcela.ValorPagoDaParcela = parcelas.ValorPagoDaParcela;
            parcela.AtualizarStatus(parcelas.StatusDaParcela);
            _parcelas.Atualizar(parcela);
            return Json(parcela.VendaId, JsonRequestBehavior.AllowGet);
        }

        public JsonResult BuscarParcelasPorVenda(string nome)
        {
            var parcelas = _venda.BuscarPorNome(nome)
                                .Where(x => x.StatusDaVenda == true)
                                .Select(x => new
                                          {
                                             label = $"{x.Cliente.Nome} - " +
                                                     $"{x.Cliente.Cpf} - " +
                                                     $"{x.Lote.Quadra.Loteamento.Nome} - " +
                                                     $"{x.Lote.Quadra.IdentificacaoDaQuadra} - " +
                                                     $"{x.Lote.IdentificacaoDoLote}",
                                             id = x.VendaId
                                          }).ToList();
            return Json(parcelas, JsonRequestBehavior.AllowGet);
        }

        public ActionResult PreencherTabela(Guid id)
        {
            var parcelas = _parcelas.BuscarTodosPorVenda(id);
            return PartialView("_TabelaParcelas", parcelas);
        }

        public ActionResult ObterModalParaAtualizarParcelas(Guid id)
        {
            var parcela = _parcelas.BuscarPorId(id);
            return PartialView("_ModalConfirmacao", parcela);
        }
    }
}

Eloenay_Tcc/Eloenay_Tcc/Views/Parcela/Index.cshtml
@model Eloenay_Tcc.Models.Parcela
@{
    ViewBag.Title = "Index";
}

@section styles{
    @Styles.Render("~/Content/site-css")
    @Styles.Render("~/Content/autocomplete-css")
}

<header class="sgvl-header">
    <h1 class="ui header">
        <span class="content sgvl-text-uppercase">Parcelas</span>
    </h1>
</header>

<article class="ui basic segment sgvl-article">
    <div class="ui fluid large action input" id="parcelas" data-url="@Url.Action("BuscarParcelasPorVenda", "Parcela")">
        @Html.TextBox("Cliente_Nome", string.Empty, new { @class = "", placeholder = "Pesquisar por cliente" })
        <button class="ui button busca" id="btnPesquisarParcelas">Pesquisar</button>
        @Html.HiddenFor(model => model.VendaId)
    </div>
    <br />
    <hr />
    <div id="tabelaParcelas" data-url="@Url.Action("PreencherTabela", "Parcela")"></div>

    <div class="ui tiny modal modalStatus"></div>
</article>

@section scripts {
    @Scripts.Render("~/bundles/autocomplete-js")
    @Scripts.Render("~/bundles/jquery-ui-js")
    @Scripts.Render("~/bundles/parcelas-js")
}

Eloenay_Tcc/Eloenay_Tcc/Views/Parcela/_ModalConfirmacao.cshtml
@model Eloenay_Tcc.Models.Parcela

<div class="header">
    Confirmar Pagamento
</div>
<div class="content">
    <p>Essa parcela já foi paga?</p>
    <form class="ui form parcela-atualizar">
        <div class="ui aligned segment">
            @Html.HiddenFor(x => x.ParcelaId)
            <div class="field">
                @Html.Label("Valor da Parcela")
                @Html.HiddenFor(x => x.ValorDaParcela)
                @Html.TextBoxFor(x => x.ValorParcelaFormt, new { disabled = "disabled" })
            </div>
            <div class="field">
                @Html.Label("Valor Pago")
                @Html.TextBoxFor(x => x.ValorPagoDaParcela, new { @class = "ValorPagoParcela" })
                <div class="msg-valor"></div>
            </div>
        </div>
    </form>
</div>
<div class="actions">
    <div class="ui negative button btnNaoStatus">
        Não
    </div>
    <div class="ui positive right button btnSimStatus" data-url="@Url.Action("Atualizar", "Parcela")">
        Sim
    </div>
</div>

Eloenay_Tcc/Eloenay_Tcc/Views/Parcela/_TabelaParcelas.cshtml
@model IEnumerable<Eloenay_Tcc.Models.Parcela>

<table class="ui very basic table sgvl-datatable">
    @if (Model.Any(x => x.ParcelaId != null))
    {
        <thead>
            <tr>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>

            @foreach (var parcela in Model)
                {
                <tr>
                    <td>
                        @Html.HiddenFor(modelItem => parcela.ParcelaId)
                        <b>Identificação: </b>
                        @Html.DisplayFor(modelItem => parcela.IdentificacaoParcela)
                        <br />
                        <b>Data de Vencimento: </b>
                        @Html.DisplayFor(modelItem => parcela.DataParcelaFormt)
                        <br />
                    </td>
                    @if (parcela.StatusDaParcela == false)
                    {
                        <td>
                            <b>Valor da parcela: </b>
                            @Html.DisplayFor(modelItem => parcela.ValorParcelaFormt)
                        </td>
                        <td></td>
                    }
                    else
                    {
                        <td>
                            <b>Valor da parcela: </b>
                            @Html.DisplayFor(modelItem => parcela.ValorParcelaFormt)
                        </td>
                        <td>
                            <b>Valor pago: </b>
                            @Html.DisplayFor(modelItem => parcela.ValorPagoParcelaFormt)
                        </td>
                    }
                    <td>
                        <b>Status: </b>
                        @if (parcela.StatusDaParcela == true)
                        {
                            <button type="button" class="ui mini green button sgvl-text-uppercase">Pago</button>
                        }
                        @if (parcela.DataDaParcela.Date < DateTime.Now.Date && parcela.StatusDaParcela == false)
                        {
                            <a class="ui mini red button sgvl-text-uppercase statusBtn" data-url="@Url.Action("ObterModalParaAtualizarParcelas", "Parcela", new {id = parcela.ParcelaId})">Atrasado</a>
                        }
                        @if (parcela.DataDaParcela.Date >= DateTime.Now.Date && parcela.StatusDaParcela == false)
                        {
                            <a class="ui mini yellow button sgvl-text-uppercase statusBtn" data-url="@Url.Action("ObterModalParaAtualizarParcelas", "Parcela", new {id = parcela.ParcelaId})">Pendente</a>
                        }
                    </td>
                </tr>
            }
        </tbody>
    }
    else
    {
        <tr>
            <td>
                <h3 style="text-align:center">Nenhum registro encontrado</h3>
            </td>
        </tr>
    }
</table>
<br />