Eloenay_Tcc/Eloenay_Tcc/Controllers/ClienteController.cs
using Eloenay_Tcc.Helpers;
using Eloenay_Tcc.Models;
using Eloenay_Tcc.ViewModels;
using PagedList;
using System;
using System.Web.Mvc;

namespace Eloenay_Tcc.Controllers
{
    [Authorize]
    public class ClienteController : Controller
    {
        private readonly Cliente _cliente;

        public ClienteController(Cliente cliente)
        {
            _cliente = cliente;
        }

        public ActionResult Index(string busca = "", int pagina = 1)
        {
            var cliente = _cliente.BuscarPorNome(busca).ToPagedList(pagina, 6);
            ViewBag.Busca = busca;
            return View(cliente);
        }

        public ActionResult Adicionar()
        {
            return View();
        }

        public ActionResult Atualizar(Guid id)
        {
            var clientes = _cliente.BuscarPorId(id);
            return View(clientes);
        }

        public ActionResult Detalhes(Guid id)
        {
            var clientes = _cliente.BuscarPorId(id);
            return View(clientes);
        }

        [HttpPost]
        public ActionResult Adicionar(Cliente cliente)
        {
            if (!ModelState.IsValid) return View(cliente).Error("Erro ao cadastrar cliente");
            cliente.UsuarioId = Account.UsuarioId;
            _cliente.Adicionar(cliente);
            return RedirectToAction("Index").Success("Cliente cadastrado com sucesso");
        }

        [HttpPost]
        public ActionResult Atualizar(Cliente cliente)
        {
            if (!ModelState.IsValid) return View(cliente).Error("Erro ao atualizar cliente");
            cliente.UsuarioId = Account.UsuarioId;
            _cliente.Atualizar(cliente);
            return RedirectToAction("Index").Success("Cliente atualizado com sucesso");
        }
    }
}

Eloenay_Tcc/Eloenay_Tcc/Controllers/LoteController.cs
using Eloenay_Tcc.Helpers;
using Eloenay_Tcc.Models;
using System;
using System.Linq;
using System.Web.Mvc;

namespace Eloenay_Tcc.Controllers
{
    [Authorize]
    public class LoteController : Controller
    {
        private readonly Lote _lote;
        private readonly Quadra _quadra;
        private readonly Loteamento _loteamento;

        public LoteController(Lote lote, Quadra quadra, Loteamento loteamento)
        {
            _lote = lote;
            _quadra = quadra;
            _loteamento = loteamento;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Adicionar()
        {
            return View();
        }

        public ActionResult Atualizar(Guid id)
        {
            var lote = _lote.BuscarPorId(id);
            return View(lote);
        }

        public ActionResult Detalhes(Guid id)
        {
            var lote = _lote.BuscarPorId(id);
            return View(lote);
        }

        [HttpPost]
        public ActionResult Adicionar(Lote lote, double largura, double comprimento)
        {
            if (!ModelState.IsValid) return View(lote).Error("Erro ao cadastrar lote");
            lote.CalcularMetrosQuadrados(largura, comprimento);
            _lote.Adicionar(lote);
            return RedirectToAction("Index").Success("Lote cadastrado com sucesso");
        }

        [HttpPost]
        public ActionResult Atualizar(Lote lote, double largura, double comprimento)
        {
            if (!ModelState.IsValid) return View(lote).Error("Erro ao atualizar lote");
            lote.CalcularMetrosQuadrados(largura, comprimento);
            var loteAtual = _lote.BuscarPorId(lote.LoteId);
            loteAtual.AtualizarDados(lote);
            _lote.Atualizar(loteAtual);
            return RedirectToAction("Index").Success("Lote atualizado com sucesso");
        }

        public ActionResult PreencherTabela(Guid id)
        {
            var lotesPorQuadra = _lote.ObterLotePorQuadra(id);
            return PartialView("_TabelaLote", lotesPorQuadra);
        }

        public JsonResult ObterLoteamento()
        {
            var loteamento = _loteamento.BuscarTodos();
            return Json(loteamento.Select(x => $"<option value='{x.LoteamentoId}'>{x.Nome}</option>"), JsonRequestBehavior.AllowGet);
        }

        public JsonResult ObterQuadraPorLoteamento(Guid loteamentoId)
        {
            var quadra = _quadra.ObterQuadraPorLoteamento(loteamentoId);
            return Json(quadra.Select(x => $"<option value='{x.QuadraId}'>{x.IdentificacaoDaQuadra}</option>"), JsonRequestBehavior.AllowGet);
        }
    }
}

Eloenay_Tcc/Eloenay_Tcc/Controllers/QuadraController.cs
using Eloenay_Tcc.Helpers;
using Eloenay_Tcc.Models;
using PagedList;
using System;
using System.Linq;
using System.Web.Mvc;

namespace Eloenay_Tcc.Controllers
{
    [Authorize]
    public class QuadraController : Controller
    {
        private readonly Quadra _quadra;
        private readonly Loteamento _loteamento;
        public QuadraController(Quadra quadra, Loteamento loteamento)
        {
            _quadra = quadra;
            _loteamento = loteamento;
        }

        public ActionResult Index(string busca = "", int pagina = 1)
        {
            var quadra = _quadra.BuscarPorNome(busca).ToPagedList(pagina, 7);
            ViewBag.Busca = busca;
            return View(quadra);
        }

        public ActionResult Adicionar()
        {
            return View();
        }

        public ActionResult Atualizar(Guid id)
        {
            var quadra = _quadra.BuscarPorId(id);
            return View(quadra);
        }

        public ActionResult Detalhes(Guid id)
        {
            var quadra = _quadra.BuscarPorId(id);
            return View(quadra);
        }

        [HttpPost]
        public ActionResult Adicionar(Quadra quadra, double largura, double comprimento)
        {
            if (!ModelState.IsValid) return View(quadra).Error("Erro ao cadastrar quadra");
            quadra.CalcularMetrosQuadrados(largura, comprimento);
            _quadra.Adicionar(quadra);
            return RedirectToAction("Index").Success("Quadra cadastrada com sucesso");
        }

        [HttpPost]
        public ActionResult Atualizar(Quadra quadra, double largura, double comprimento)
        {
            if (!ModelState.IsValid) return View(quadra).Error("Erro ao atualizar quadra");
            quadra.CalcularMetrosQuadrados(largura, comprimento);
            _quadra.Atualizar(quadra);
            return RedirectToAction("Index").Success("Quadra atualizada com sucesso");
        }

        public JsonResult ObterLoteamento()
        {
            var loteamento = _loteamento.BuscarTodos();
            return Json(loteamento.Select(x => $"<option value='{x.LoteamentoId}'>{x.Nome}</option>"), JsonRequestBehavior.AllowGet);
        }
    }
}

Eloenay_Tcc/Eloenay_Tcc/Controllers/VendaController.cs
using Eloenay_Tcc.Helpers;
using Eloenay_Tcc.Models;
using Eloenay_Tcc.ViewModels;
using PagedList;
using System;
using System.Linq;
using System.Web.Mvc;

namespace Eloenay_Tcc.Controllers
{
    [Authorize]
    public class VendaController : Controller
    {
        private readonly Venda _venda;
        private readonly Cliente _cliente;
        private readonly Loteamento _loteamento;
        private readonly Lote _lote;
        private readonly Quadra _quadra;
        private readonly Parcela _parcelas;

        public VendaController(Venda venda, Cliente cliente, Loteamento loteamento, Lote lote, Quadra quadra, Parcela parcelas)
        {
            _venda = venda;
            _cliente = cliente;
            _loteamento = loteamento;
            _lote = lote;
            _quadra = quadra;
            _parcelas = parcelas;
        }

        public ActionResult Index(string buscaFinalizada = "", int pagina = 1)
        {
            var vendas = _venda.BuscarPorNome(buscaFinalizada).Where(x => x.StatusDaVenda == true).ToPagedList(pagina, 7);
            ViewBag.Busca = buscaFinalizada;
            return View(vendas);
        }

        [Route("Venda/Index/Canceladas")]
        public ActionResult VendasCanceladas(string buscaCancelada = "", int pagina = 1)
        {
            var vendas = _venda.BuscarPorNome(buscaCancelada).Where(x => x.StatusDaVenda == false).ToPagedList(pagina, 7);
            ViewBag.BuscaCancelada = buscaCancelada;
            return View(vendas);
        }

        public ActionResult Adicionar()
        {
            return View();
        }

        [Route("Venda/Adicionar/{id}")]
        public ActionResult AdicionarVendaPelaHome(Guid id)
        {
            var lote = _lote.BuscarPorId(id);
            ViewBag.LoteId = lote.LoteId;
            ViewBag.LoteIdentificacao = lote.IdentificacaoDoLote;
            ViewBag.LoteQuadra = lote.Quadra.IdentificacaoDaQuadra;
            ViewBag.LoteValor = lote.ValorDoLote;
            return View("Adicionar");
        }

        public ActionResult Detalhes(Guid id)
        {
            ViewBag.ValorParcela = string.Format("{0:#,0.00}", _parcelas.ObterValorParcela(id).ValorDaParcela);
            var vendas = _venda.BuscarPorId(id);
            return View(vendas);
        }

        [HttpPost]
        public ActionResult Adicionar(Venda venda, decimal valorEntrada, int quantidadeDeParcelas, double juros, DateTime primeiraParcela)
        {
            ModelState.Remove(nameof(venda.Lote));
            var lote = _lote.BuscarPorId(venda.LoteId);
            venda.Lote = lote;
            venda.UsuarioId = Account.UsuarioId;
            _venda.AtribuirValores(venda);
            lote.AtualizarStatus();
            _lote.Atualizar(lote);
            _venda.Adicionar(venda);

            var valorParcelas = _parcelas.ValorDasParcelas(lote.ValorDoLote, valorEntrada, quantidadeDeParcelas, juros);
            _parcelas.CriarParcelas(venda.VendaId, primeiraParcela, quantidadeDeParcelas, valorParcelas);
            return RedirectToAction("Detalhes", new { id = venda.VendaId }).Success("Venda realizada com sucesso");
        }

        #region Json
        public ActionResult CancelarVenda(Guid id)
        {
            var cancelarVenda = _venda.BuscarPorId(id);
            var lote = _lote.BuscarPorId(cancelarVenda.Lote.LoteId);
            cancelarVenda.AtualizarStatus();
            lote.AtualizarStatus();
            _venda.Atualizar(cancelarVenda);
            _lote.Atualizar(lote);
            return Json(cancelarVenda.VendaId, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult AdicionarCliente(Cliente cliente)
        {
            if (!ModelState.IsValid) return View("Adicionar");
            cliente.UsuarioId = Account.UsuarioId;
            _cliente.Adicionar(cliente);
            return Json(cliente, JsonRequestBehavior.AllowGet);
        }

        public ActionResult BuscarVendaParaCancelar(Guid id)
        {
            var venda = _venda.BuscarPorId(id);
            return PartialView("_ModalCancelarVendas", venda);
        }

        public JsonResult ObterClienteParaAutocomplete(string nome)
        {
            var clientes = _cliente.BuscarPorNome(nome).Select(x => new { label = x.Nome, id = x.ClienteId, cpf = x.Cpf, dataNasc = x.DataNascimento.ToShortDateString() }).ToList();
            return Json(clientes, JsonRequestBehavior.AllowGet);
        }

        public JsonResult ObterLoteDaHomeParaVenda(Guid id)
        {
            var lotes = _lote.BuscarLote(id).Select(x => new { id = x.LoteId, name = x.IdentificacaoDoLote, quadra = x.Quadra.IdentificacaoDaQuadra, valor = x.ValorDoLote }).ToList();
            return Json(lotes, JsonRequestBehavior.AllowGet);
        }

        public JsonResult ObterLoteamento()
        {
            var loteamento = _loteamento.BuscarTodos();
            return Json(loteamento.Select(x => $"<option value='{x.LoteamentoId}'>{x.Nome}</option>"), JsonRequestBehavior.AllowGet);
        }

        public JsonResult ObterQuadraPorLoteamento(Guid loteamentoId)
        {
            var quadra = _quadra.ObterQuadraPorLoteamento(loteamentoId);
            return Json(quadra.Select(x => $"<option value='{x.QuadraId}'>{x.IdentificacaoDaQuadra}</option>"), JsonRequestBehavior.AllowGet);
        }

        public JsonResult ObterLotePorQuadra(Guid quadraId)
        {
            var lote = _lote.ObterLotePorQuadra(quadraId).Where(x => x.StatusDoLote == true);
            return Json(lote.Select(x => $"<option value='{x.LoteId}'>{x.IdentificacaoDoLote}</option>"), JsonRequestBehavior.AllowGet);
        }

        public ActionResult ModalCadastrarClienteVenda()
        {
            return PartialView("_ModalCadastrarCliente");
        }

        public ActionResult ModalBuscarLoteVenda()
        {
            return PartialView("_ModalBuscarLote");
        }

        public JsonResult BuscarContratoDeVendas(Guid id)
        {
            var venda = _venda.BuscarPorId(id);
            var primeParcela = venda.Parcelas.OrderBy(x => x.DataDaParcela).FirstOrDefault();
            var ultiParcela = venda.Parcelas.OrderByDescending(x => x.DataDaParcela).FirstOrDefault();
            var valorDaParcela = venda.Parcelas.FirstOrDefault();
            var model = new
            {
                dataCompra = venda.DataCompraFormat,
                dataCancelamento = venda.DataCancelamentoFormat,
                multa = venda.MultaDeRescisao,
                valorEntrada = venda.ValorEntradaFormat,
                parcelasPagas = venda.ParcelaPaga,
                valorParcelas = valorDaParcela.ValorParcelaFormt,
                primeiraParcela = primeParcela.DataParcelaFormt,
                ultimaParcela = ultiParcela.DataParcelaFormt,
                valorDevolucao = venda.ValorDevolucao,
                valorDesconto = venda.ValorDescontado,
                //Dados do Proprietario para contrato
                nomeProp = venda.Lote.Quadra.Loteamento.Proprietario.Nome,
                nascionalidadeProp = venda.Lote.Quadra.Loteamento.Proprietario.Nacionalidade,
                estadoCivilProp = venda.Lote.Quadra.Loteamento.Proprietario.EstadoCivil,
                ocupacaoProp = venda.Lote.Quadra.Loteamento.Proprietario.Ocupacao,
                rgProp = venda.Lote.Quadra.Loteamento.Proprietario.Rg,
                orgaoExpedidorProp = venda.Lote.Quadra.Loteamento.Proprietario.OrgaoExpedidor,
                cpfProp = venda.Lote.Quadra.Loteamento.Proprietario.Cpf,
                enderecoProp = venda.Lote.Quadra.Loteamento.Proprietario.Endereco,
                numeroProp = venda.Lote.Quadra.Loteamento.Proprietario.Numero,
                bairroProp = venda.Lote.Quadra.Loteamento.Proprietario.Bairro,
                cidadeProp = venda.Lote.Quadra.Loteamento.Proprietario.Cidade,
                estadoProp = venda.Lote.Quadra.Loteamento.Proprietario.Estado,
                //Dados do Cliente para contrato
                nomeCliente = venda.Cliente.Nome,
                nascionalidadeCliente = venda.Cliente.Nacionalidade,
                estadoCivilCliente = venda.Cliente.EstadoCivil,
                ocupacaoCliente = venda.Cliente.Ocupacao,
                rgCliente = venda.Cliente.Rg,
                orgaoExpedidorCliente = venda.Cliente.OrgaoExpedidor,
                cpfCliente = venda.Cliente.Cpf,
                enderecoCliente = venda.Cliente.Endereco,
                numeroCliente = venda.Cliente.Numero,
                bairroCliente = venda.Cliente.Bairro,
                cidadeCliente = venda.Cliente.Cidade,
                estadoCliente = venda.Cliente.Estado,
                //Dados de Lote, Quadra e Loteamento
                identificacaoLote = venda.Lote.IdentificacaoDoLote,
                metrosQuadradosLote = venda.Lote.MetroQuadradoLote,
                valorLote = string.Format("{0:#,0.00}", venda.Lote.ValorDoLote),
                identificacaoQuadra = venda.Lote.Quadra.IdentificacaoDaQuadra,
                nomeLoteamento = venda.Lote.Quadra.Loteamento.Nome,
                matriculaLoteamento = venda.Lote.Quadra.Loteamento.Matricula,
                bairroLoteamento = venda.Lote.Quadra.Loteamento.Endereco,
                enderecoLoteamento = venda.Lote.Quadra.Loteamento.Bairro,
                cidadeLoteamento = venda.Lote.Quadra.Loteamento.Cidade,

            };
            return Json(model, JsonRequestBehavior.AllowGet);
        }
        #endregion
    }
}

Eloenay_Tcc/Eloenay_Tcc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/basic-css")
    @RenderSection("styles", required: false)
    @Scripts.Render("~/bundles/modernizr-js")
    <link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.1.8/components/icon.min.css'>

</head>
<body>
    <nav class="sgvl-navigation-left">
        <div class="big ui buttons item">
            @Html.ActionLink("SGVL - LOTEAMENTO", "Index", "Home", new { area = "" }, new { @class = "ui inverted button sgvl-text-uppercase sgvl-titulo" })
            <a onclick="SGVL.OnpenMenu(this);" class="ui inverted icon button center aligned"><i class="sidebar icon"></i></a>
        </div>

        <div class="fluid big ui inverted vertical menu">
            <div class="item sgvl-menu-execucao">
                <div class="item sgvl-p-0"></div>
                <div class="item sgvl-menu-itens">
                    <div class="ui top left floating item">
                        <a class="item" id="btnCliente" data-url="@Url.Action("Index","Cliente")">Cliente</a>
                        <a class="item" id="btnProprietario" data-url="@Url.Action("Index","Proprietario")">Proprietario</a>
                        <a class="item" id="btnLoteamento" data-url="@Url.Action("Index","Loteamento")">Loteamento</a>
                        <a class="item" id="btnQuadra" data-url="@Url.Action("Index","Quadra")">Quadra</a>
                        <a class="item" id="btnLote" data-url="@Url.Action("Index","Lote")">Lote</a>
                        <a class="item" id="btnVenda" data-url="@Url.Action("Index","Venda")">Venda</a>
                        <a class="item" id="btnParcela" data-url="@Url.Action("Index","Parcela")">Parcelas</a>
                    </div>
                </div>
            </div>

            @if (User.Identity.IsAuthenticated)
            {
                <div class="item sgvl-menu-settings">
                    <a href="@Url.Action("AlterarSenha","Login")" class="item dropdown" data-toggle="dropdown">@User.Identity.Name<span class="caret"></span></a>
                    <a class="item" href="@Url.Action("Logout","Login")">Sair</a>
                </div>
            }
        </div>
    </nav>
    <main class="sgvl-main">
        <div class="sgvl-container">
            @RenderBody()
        </div>
        <footer class="sgvl-footer sgvl-text-uppercase">
            <p>&copy; @DateTime.Now.Year <a href="@Url.Action("Cadastrar", "Login")" style="cursor:text"> - </a> Eloenay Pereira</p>
        </footer>
    </main>
    @Scripts.Render("~/bundles/basic-js")
    @Scripts.Render("~/bundles/menu-layout-js")
    @RenderSection("scripts", required: false)
    @Html.Partial("_Notify")
</body>
</html>

Eloenay_Tcc/Eloenay_Tcc/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SGVL-Loteamentos</title>
    @RenderSection("styles", required: false)
    @Scripts.Render("~/bundles/modernizr-js")

</head>
<body>
    <main class="sgvl-main">
        <div class="sgvl-container">
            @RenderBody()
        </div>
    </main>
    @Scripts.Render("~/bundles/basic-js")
    @RenderSection("scripts", required: false)
    @Html.Partial("_Notify")
</body>
</html>

Eloenay_Tcc/Eloenay_Tcc/Views/Shared/_Notify.cshtml
<script>
    @if (TempData["Success"] != null)
    {
        @:Lobibox.notify('success', { position: 'top right', sound: '../../sounds/sound2', delay: 3000, msg: '@TempData["Success"]', title: 'Sucesso', icon: 'smile icon' });
    }
    else if (TempData["Error"] != null)
    {
        @:Lobibox.notify('error', { position: 'top right', sound: '../../sounds/sound4', delay: 3000, msg: '@Html.Raw(TempData["Error"])', title: 'Erro', icon: 'frown icon' });
    }
    else if (TempData["Alert"] != null)
    {
        @:Lobibox.notify('warning', { position: 'top right', sound: '../../sounds/sound5', delay: 3000, msg: '@TempData["Alert"]', title: 'Alerta', icon: 'warning icon' });
    }
    else if (TempData["Information"] != null)
    {
        @:Lobibox.notify('info', { position: 'top right', sound: '../../sounds/sound6', delay: 3000, msg: '@TempData["Information"]', title: 'Informação', icon: 'info circle icon' });
    }
</script>