Eloenay_Tcc/Eloenay_Tcc/Controllers/LoteamentoController.cs
using Eloenay_Tcc.Helpers;
using Eloenay_Tcc.Models;
using PagedList;
using System;
using System.Linq;
using System.Web.Mvc;

namespace Eloenay_Tcc.Controllers
{
    [Authorize]
    public class LoteamentoController : Controller
    {
        public readonly Loteamento _loteamento;
        public readonly Proprietario _proprietario;

        public LoteamentoController(Loteamento loteamento, Proprietario proprietario)
        {
            _loteamento = loteamento;
            _proprietario = proprietario;
        }

        public ActionResult Index(string busca = "", int pagina = 1)
        {
            var loteamentos = _loteamento.BuscarPorNome(busca).ToPagedList(pagina, 7);
            ViewBag.Busca = busca;
            return View(loteamentos);
        }

        public ActionResult Adicionar()
        {
            return View();
        }

        public ActionResult Atualizar(Guid id)
        {
            var loteamentos = _loteamento.BuscarPorId(id);
            return View(loteamentos);
        }

        public ActionResult Detalhes(Guid id)
        {
            var loteamentos = _loteamento.BuscarPorId(id);
            return View(loteamentos);
        }

        [HttpPost]
        public ActionResult Adicionar(Loteamento loteamento)
        {
            if (!ModelState.IsValid) return View(loteamento).Error("Erro ao cadastrar loteamento");
            _loteamento.Adicionar(loteamento);
            return RedirectToAction("Index").Success("Loteamento cadastrado com sucesso");
        }

        [HttpPost]
        public ActionResult Atualizar(Loteamento loteamento)
        {
            if (!ModelState.IsValid) return View(loteamento).Error("Erro ao atualizar loteamento");
            _loteamento.Atualizar(loteamento);
            return RedirectToAction("Index").Success("Loteamento atualizado com sucesso");
        }

        public JsonResult ObterProprietario()
        {
            var proprietario = _proprietario.BuscarTodos();
            return Json(proprietario.Select(x => $"<option value='{x.ProprietarioId}'>{x.Nome}</option>"), JsonRequestBehavior.AllowGet);
        }
    }
}

Eloenay_Tcc/Eloenay_Tcc/Views/Loteamento/Adicionar.cshtml
@{
    ViewBag.Title = "Adicionar";
}

@section styles{
    @Styles.Render("~/Content/site-css")
}

<header class="sgvl-header">
    <h1 class="ui header">
        <span class="content sgvl-text-uppercase">ADICIONAR</span>
    </h1>
</header>

<article class="ui basic segment sgvl-article">
    @using (Html.BeginForm("Adicionar", "Loteamento", new { area = "" }, FormMethod.Post, new { @class = "ui form" }))
    {
        @Html.AntiForgeryToken()
        @Html.Partial("_Form")
    }
</article>

@section Scripts {
    @Scripts.Render("~/bundles/mask-js")
    @Scripts.Render("~/bundles/validar-campos-js")
    @Scripts.Render("~/bundles/preencher-drop-js")
}

Eloenay_Tcc/Eloenay_Tcc/Views/Loteamento/Atualizar.cshtml
@model Eloenay_Tcc.Models.Loteamento
@{
    ViewBag.Title = "Atualizar";
}

@section styles{
    @Styles.Render("~/Content/site-css")
}

<header class="sgvl-header">
    <h1 class="ui header">
        <span class="content sgvl-text-uppercase">ATUALIZAR</span>
    </h1>
</header>

<article class="ui basic segment sgvl-article">
    @using (Html.BeginForm("Atualizar", "Loteamento", new { area = "" }, FormMethod.Post, new { @class = "ui form" }))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(l => l.ProprietarioId)
        @Html.HiddenFor(l => l.LoteamentoId)
        @Html.Partial("_Form")
    }
</article>

@section Scripts {
    @Scripts.Render("~/bundles/mask-js")
    @Scripts.Render("~/bundles/validar-campos-js")
    @Scripts.Render("~/bundles/preencher-drop-js")
}

Eloenay_Tcc/Eloenay_Tcc/Views/Loteamento/Detalhes.cshtml
@model Eloenay_Tcc.Models.Loteamento
@{
    ViewBag.Title = "Detalhes";
}

@section styles{
    @Styles.Render("~/Content/site-css")
}

<header class="sgvl-header">
    <h1 class="ui header">
        <span class="content sgvl-text-uppercase">Detalhes</span>
    </h1>
</header>

<article class="ui basic segment sgvl-article">
    <div class="ui stackable column grid divided sgvl-grid-details">
        <div class="two column row">
            <div class="ten wide column">
                <h4 class="ui header">Nome Loteamento</h4>
                @Model.Nome
            </div>
            <div class="six wide column">
                <h4 class="ui header">@Html.DisplayNameFor(model => model.Matricula)</h4>
                @Model.Matricula
            </div>
        </div>
        <div class="two column row">
            <div class="six wide column">
                <h4 class="ui header">Metros Quadrado</h4>
                @Model.MetrosQuadrados
            </div>
            <div class="ten wide column">
                <h4 class="ui header">Proprietário</h4>
                @Model.Proprietario.Nome
            </div>
        </div>
        <div class="three column row">
            <div class="seven wide column">
                <h4 class="ui header">Endereço</h4>
                @Model.Endereco
            </div>
            <div class="two wide column">
                <h4 class="ui header">Número</h4>
                @Model.Numero
            </div>
            <div class="seven wide column">
                <h4 class="ui header">@Html.DisplayNameFor(model => model.Bairro)</h4>
                @Model.Bairro
            </div>
        </div>
        <div class="three column row">
            <div class="column">
                <h4 class="ui header">@Html.DisplayNameFor(model => model.Cep)</h4>
                @Model.Cep
            </div>
            <div class="column">
                <h4 class="ui header">@Html.DisplayNameFor(model => model.Cidade)</h4>
                @Model.Cidade
            </div>
            <div class="column">
                <h4 class="ui header">@Html.DisplayNameFor(model => model.Estado)</h4>
                @Model.Estado
            </div>
        </div>

        <a class="ui large button left floated sgvl-text-uppercase retornar" href="@Url.Action("Index", "Loteamento", new { })">Retornar</a>
    </div>
</article>

Eloenay_Tcc/Eloenay_Tcc/Views/Loteamento/Index.cshtml
@using PagedList.Mvc;
@model PagedList.PagedList<Eloenay_Tcc.Models.Loteamento>

@{
    ViewBag.Title = "Index";
}
@section styles{
    @Styles.Render("~/Content/paged-list-css")
    @Styles.Render("~/Content/site-css")
}

<header class="sgvl-header">
    <h1 class="ui header">
        <span class="content sgvl-text-uppercase">Loteamento</span>
    </h1>
</header>

<article class="ui basic segment sgvl-article">

    @using (Html.BeginForm("Index", "Loteamento", FormMethod.Get, new { @class = "ui form" }))
    {
        <a class="ui medium button right floated blue sgvl-text-uppercase" id="btnAdicionar" href="@Url.Action("Adicionar", "Loteamento", new {  })" data-loading="btn" title="Adicionar">Adicionar</a>

        <div class="ui medium input action">
            <input class="" id="busca" type="text" placeholder="Buscar Loteamento..." name="busca" value="@ViewBag.Busca">
            <button class="ui button busca" type="submit"><i class="search icon"></i></button>
        </div>
    }

    <table class="ui very basic table sgvl-datatable">
        @if (Model.Any(x => x.LoteamentoId != null))
        {
            <thead>
                <tr>
                    <th class="eight wide"></th>
                    <th class="three wide"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var loteamento in Model)
                {
                    <tr>
                        <td>
                            <b>Nome: </b>
                            @Html.DisplayFor(modelItem => loteamento.Nome)
                            <br />
                            <b>Matricula: </b>
                            @Html.DisplayFor(modelItem => loteamento.Matricula)
                            <br />
                            <b>Proprietário: </b>
                            @Html.DisplayFor(modelItem => loteamento.Proprietario.Nome)
                            <br />
                        </td>
                        <td>
                            <a class="ui mini button detalhes" id="btnDetalhes" href="@Url.Action("Detalhes", "Loteamento", new { id = loteamento.LoteamentoId })" title="Detalhes"><i class="sgvl-icon list icon"></i></a>
                            <a id="btnAtualizar" href="@Url.Action("Atualizar", "Loteamento", new { id = loteamento.LoteamentoId })" class="ui mini button editar" title="Editar"><i class="edit icon sgvl-icon"></i></a>
                        </td>
                    </tr>
                }
            </tbody>
        }
        else
        {
            <tr>
                <td>
                    <h3 style="text-align:center">Nenhum registro encontrado</h3>
                </td>
            </tr>
        }
    </table>
    <br />

    <div id="paginacao">@Html.PagedListPager(Model, pagina => Url.Action("Index", new { pagina, busca = ViewBag.Busca }))</div>
</article>

Eloenay_Tcc/Eloenay_Tcc/Views/Loteamento/_Form.cshtml
@model Eloenay_Tcc.Models.Loteamento

<div class="fields">
    <div class="twelve wide field">
        @Html.Label("Nome Loteamento")
        @Html.TextBoxFor(model => model.Nome, new { })
    </div>
    <div class="six wide field">
        @Html.LabelFor(model => model.Matricula)
        @Html.TextBoxFor(model => model.Matricula, new { })
    </div>
</div>

<div class="three fields" data-pd="pr">

    <div class="six wide field">
        @Html.Label("Metros Quadrado")
        @Html.TextBoxFor(model => model.MetrosQuadrados, new { @class = "medida" })
    </div>
    <div class="ui action twelve wide field" data-pd-pr="proprietario">
        @Html.Label("Proprietário")
        @Html.DropDownList("ProprietarioId", Enumerable.Empty<SelectListItem>(), "", new
       {
           @class = "fluid selection ui dropdown",
           data_pd_url = Url.Action("ObterProprietario", "Loteamento", new { }),
           data_pd_selected = Model?.ProprietarioId
       })
    </div>
</div>

<div class="fields">
    <div class="eight  wide field">
        @Html.Label("Endereço")
        @Html.TextBoxFor(model => model.Endereco, new { })
    </div>
    <div class="three wide field">
        @Html.Label("Número")
        @Html.TextBoxFor(model => model.Numero, new { })
    </div>
    <div class="eight  wide field">
        @Html.LabelFor(model => model.Bairro)
        @Html.TextBoxFor(model => model.Bairro, new { })
    </div>
</div>


<div class="three fields">
    <div class="field">
        @Html.LabelFor(model => model.Cep)
        @Html.TextBoxFor(model => model.Cep, new { @class = "cep"})
    </div>
    <div class="field">
        @Html.LabelFor(model => model.Cidade)
        @Html.TextBoxFor(model => model.Cidade, new { })
    </div>
    <div class="field">
        @Html.LabelFor(model => model.Estado)
        @Html.EnumDropDownListFor(model => model.Estado, new { @class = "ui search fluid dropdown" })
    </div>
</div>

<div class="ui divider spba-mtb-2rem"></div>

<div class="field">
    <button class="ui large button right floated sgvl-text-uppercase confirmar" type="submit">Confirmar</button>
    <a class="ui large button left floated sgvl-text-uppercase retornar" href="@Url.Action("Index", "Loteamento", new { })">Retornar</a>
</div>