Eloenay_Tcc/Eloenay_Tcc/Controllers/ProprietarioController.cs
using Eloenay_Tcc.Helpers;
using Eloenay_Tcc.Models;
using Eloenay_Tcc.ViewModels;
using PagedList;
using System;
using System.Web.Mvc;

namespace Eloenay_Tcc.Controllers
{
    [Authorize]
    public class ProprietarioController : Controller
    {
        public readonly Proprietario _proprietario;

        public ProprietarioController(Proprietario proprietario)
        {
            _proprietario = proprietario;
        }

        public ActionResult Index(string busca = "", int pagina = 1)
        {
            var proprietarios = _proprietario.BuscarPorNome(busca).ToPagedList(pagina, 7);
            ViewBag.Busca = busca;
            return View(proprietarios);
        }

        public ActionResult Adicionar()
        {
            return View();
        }

        public ActionResult Atualizar(Guid id)
        {
            var proprietarios = _proprietario.BuscarPorId(id);
            return View(proprietarios);
        }

        public ActionResult Detalhes(Guid id)
        {
            var proprietarios = _proprietario.BuscarPorId(id);
            return View(proprietarios);
        }

        [HttpPost]
        public ActionResult Adicionar(Proprietario proprietario)
        {
            if (!ModelState.IsValid) return View(proprietario).Error("Error ao cadastrar proprietário");
            proprietario.UsuarioId = Account.UsuarioId;
            _proprietario.Adicionar(proprietario);
            return RedirectToAction("Index").Success("Proprietário cadastrado com sucesso");
        }

        [HttpPost]
        public ActionResult Atualizar(Proprietario proprietario)
        {
            if (!ModelState.IsValid) return View(proprietario).Error("Error ao atualizar proprietário");
            proprietario.UsuarioId = Account.UsuarioId;
            _proprietario.Atualizar(proprietario);
            return RedirectToAction("Index").Success("Proprietário atualizado com sucesso");
        }
    }
}

Eloenay_Tcc/Eloenay_Tcc/Views/Proprietario/Adicionar.cshtml
@{
    ViewBag.Title = "Adicionar";
}

@section styles
{
    @Styles.Render("~/Content/datepicker-css")
    @Styles.Render("~/Content/site-css")
}

<header class="sgvl-header">
    <h1 class="ui header">
        <span class="content">ADICIONAR</span>
    </h1>
</header>

<article class="ui basic segment sgvl-article">
    @using (Html.BeginForm("Adicionar", "Proprietario", new { area = "" }, FormMethod.Post, new { @class = "ui form" }))
    {
        @Html.AntiForgeryToken()
        @Html.Partial("_Form")
    }
</article>

@section Scripts {
    @Scripts.Render("~/bundles/mask-js")
    @Scripts.Render("~/bundles/datepicker-js")
    @Scripts.Render("~/bundles/validar-campos-js")
}

Eloenay_Tcc/Eloenay_Tcc/Views/Proprietario/Atualizar.cshtml
@model Eloenay_Tcc.Models.Proprietario
@{
    ViewBag.Title = "Atualizar";
}

@section styles
{
    @Styles.Render("~/Content/datepicker-css")
    @Styles.Render("~/Content/site-css")
}

<header class="sgvl-header">
    <h1 class="ui header">
        <span class="content sgvl-text-uppercase">ATUALIZAR</span>
    </h1>
</header>

<article class="ui basic segment sgvl-article">
    @using (Html.BeginForm("Atualizar", "Proprietario", new { area = "" }, FormMethod.Post, new { @class = "ui form" }))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(c => c.ProprietarioId)
        @Html.Partial("_Form")
    }
</article>

@section Scripts {
    @Scripts.Render("~/bundles/mask-js")
    @Scripts.Render("~/bundles/datepicker-js")
    @Scripts.Render("~/bundles/validar-campos-js")
}

Eloenay_Tcc/Eloenay_Tcc/Views/Proprietario/Detalhes.cshtml
@model Eloenay_Tcc.Models.Proprietario
@{
    ViewBag.Title = "Detalhes";
}

@section styles
{
    @Styles.Render("~/Content/site-css")
}

<header class="sgvl-header">
    <h1 class="ui header">
        <span class="content sgvl-text-uppercase">Detalhes</span>
    </h1>
</header>

<article class="ui basic segment sgvl-article">
    <div class="ui stackable column grid divided sgvl-grid-details">
        <div class="three column row">
            <div class="column">
                <h4 class="ui header">Nome Completo</h4>
                @Model.Nome
            </div>
            <div class="column">
                <h4 class="ui header">@Html.DisplayNameFor(model => model.Cpf)</h4>
                @Model.Cpf
            </div>
            <div class="column">
                <h4 class="ui header">Estado Civil</h4>
                @Model.EstadoCivil
            </div>
        </div>
        <div class="three column row">
            <div class="column">
                <h4 class="ui header">Data de Nascimento</h4>
                @Model.DataNascimentoFormt
            </div>
            <div class="column">
                <h4 class="ui header">@Html.DisplayNameFor(model => model.Rg)</h4>
                @Model.Rg
            </div>
            <div class="column">
                <h4 class="ui header">Orgão Expedidor</h4>
                @Model.OrgaoExpedidor
            </div>
        </div>
        <div class="three column row">
            <div class="column">
                <h4 class="ui header">@Html.DisplayNameFor(model => model.Nacionalidade)</h4>
                @Model.Nacionalidade
            </div>
            <div class="column">
                <h4 class="ui header">@Html.DisplayNameFor(model => model.Telefone)</h4>
                @Model.Telefone
            </div>
            <div class="column">
                <h4 class="ui header">Ocupação</h4>
                @Model.Ocupacao
            </div>
        </div>
        <div class="three column row">
            <div class="seven wide column">
                <h4 class="ui header">Endereço</h4>
                @Model.Endereco
            </div>
            <div class="two wide column">
                <h4 class="ui header">Número</h4>
                @Model.Numero
            </div>
            <div class="seven wide column">
                <h4 class="ui header">@Html.DisplayNameFor(model => model.Bairro)</h4>
                @Model.Bairro
            </div>
        </div>
        <div class="three column row">
            <div class="column">
                <h4 class="ui header">@Html.DisplayNameFor(model => model.Cep)</h4>
                @Model.Cep
            </div>
            <div class="column">
                <h4 class="ui header">@Html.DisplayNameFor(model => model.Cidade)</h4>
                @Model.Cidade
            </div>
            <div class="column">
                <h4 class="ui header">@Html.DisplayNameFor(model => model.Estado)</h4>
                @Model.Estado
            </div>
        </div>

        <a class="ui large button left floated sgvl-text-uppercase retornar" href="@Url.Action("Index", "Proprietario", new { })">Retornar</a>
    </div>
</article>

Eloenay_Tcc/Eloenay_Tcc/Views/Proprietario/Index.cshtml
@using PagedList.Mvc;
@model PagedList.PagedList<Eloenay_Tcc.Models.Proprietario>

@{
    ViewBag.Title = "Index";
}
@section styles{
    @Styles.Render("~/Content/paged-list-css")
    @Styles.Render("~/Content/site-css")
}

<header class="sgvl-header">
    <h1 class="ui header">
        <span class="content sgvl-text-uppercase">Proprietário</span>
    </h1>
</header>

<article class="ui basic segment sgvl-article">

    @using (Html.BeginForm("Index", "Proprietario", FormMethod.Get, new { @class = "ui form" }))
    {
        <a class="ui medium button right floated blue sgvl-text-uppercase" id="btnAdicionar" href="@Url.Action("Adicionar", "Proprietario", new {  })" data-loading="btn" title="Adicionar">Adicionar</a>

        <div class="ui medium input action">
            <input class="" id="busca" type="text" placeholder="Buscar Proprietário..." name="busca" value="@ViewBag.Busca">
            <button class="ui button busca" type="submit"><i class="search icon"></i></button>
        </div>
    }

    <table class="ui very basic table sgvl-datatable">
        @if (Model.Any(x => x.ProprietarioId != null))
        {
            <thead>
                <tr>
                    <th class="eight wide"></th>
                    <th class="three wide"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var proprietario in Model)
                {
                    <tr>
                        <td>
                            <b>Nome: </b>
                            @Html.DisplayFor(modelItem => proprietario.Nome)
                            <br />
                            <b>Cpf: </b>
                            @Html.DisplayFor(modelItem => proprietario.Cpf)
                            <br />
                        </td>
                        <td>
                            <a class="ui mini button detalhes" id="btnDetalhes" href="@Url.Action("Detalhes", "Proprietario", new { id = proprietario.ProprietarioId })" title="Detalhes"><i class="sgvl-icon list icon"></i></a>
                            <a id="btnAtualizar" href="@Url.Action("Atualizar", "Proprietario", new { id = proprietario.ProprietarioId })" class="ui mini button editar" title="Editar"><i class="edit icon sgvl-icon"></i></a>
                        </td>
                    </tr>
                }
            </tbody>
        }
        else
        {
            <tr>
                <td>
                    <h3 style="text-align:center">Nenhum registro encontrado</h3>
                </td>
            </tr>
        }
    </table>
    <br />

    <div id="paginacao">@Html.PagedListPager(Model, pagina => Url.Action("Index", new { pagina, busca = ViewBag.Busca }))</div>
</article>

Eloenay_Tcc/Eloenay_Tcc/Views/Proprietario/_Form.cshtml
@model Eloenay_Tcc.Models.Proprietario

<div class="three fields">
    <div class="field">
        @Html.LabelFor(model => model.Nome)
        @Html.TextBoxFor(model => model.Nome, new { })
    </div>
    <div class="field">
        @Html.LabelFor(model => model.Cpf)
        @Html.TextBoxFor(model => model.Cpf, new { @class = "cpf" })
    </div>
    <div class="field">
        @Html.LabelFor(model => model.Rg)
        @Html.TextBoxFor(model => model.Rg, new { })
    </div>
</div>

<div class="three fields">
    <div class="field">
        @Html.Label("Data de Nascimento")
        @Html.TextBoxFor(model => model.DataNascimento, new { @class = "calendario date", autocomplete = "off" })
    </div>
    <div class="field">
        @Html.Label("Estado Civil")
        @Html.EnumDropDownListFor(model => model.EstadoCivil, new { @class = "ui search fluid selection input dropdown" })
    </div>
    <div class="field">
        @Html.Label("Orgão Expedidor")
        @Html.TextBoxFor(model => model.OrgaoExpedidor, new { })
    </div>
</div>

<div class="three fields">
    <div class="field">
        @Html.LabelFor(model => model.Nacionalidade)
        @Html.TextBoxFor(model => model.Nacionalidade, new { })
    </div>
    <div class="field">
        @Html.LabelFor(model => model.Telefone)
        @Html.TextBoxFor(model => model.Telefone, new { @class = "telefone" })
    </div>
    <div class="field">
        @Html.Label("Ocupação")
        @Html.TextBoxFor(model => model.Ocupacao, new { })
    </div>
</div>

<div class="fields">
    <div class="eight  wide field">
        @Html.Label("Endereço")
        @Html.TextBoxFor(model => model.Endereco, new { })
    </div>
    <div class="three wide field">
        @Html.Label("Número")
        @Html.EditorFor(model => model.Numero, new { })
    </div>
    <div class="eight  wide field">
        @Html.LabelFor(model => model.Bairro)
        @Html.TextBoxFor(model => model.Bairro, new { })
    </div>
</div>


<div class="three fields">
    <div class="field">
        @Html.LabelFor(model => model.Cep)
        @Html.TextBoxFor(model => model.Cep, new { @class = "cep" })
    </div>
    <div class="field">
        @Html.LabelFor(model => model.Cidade)
        @Html.TextBoxFor(model => model.Cidade, new { })
    </div>
    <div class="field">
        @Html.LabelFor(model => model.Estado)
        @Html.EnumDropDownListFor(model => model.Estado, new { @class = "ui search fluid selection input dropdown" })
    </div>
</div>

<div class="ui divider spba-mtb-2rem"></div>

<div class="field">
    <button class="ui large button right floated sgvl-text-uppercase confirmar" type="submit">Confirmar</button>
    <a class="ui large button left floated sgvl-text-uppercase retornar" href="@Url.Action("Index", "Proprietario", new { })">Retornar</a>
</div>